apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: catalogue-api
  description: API for product catalogue operations
spec:
  type: openapi
  lifecycle: production
  owner: backend-team
  system: sock-shop
  definition:
    $text: https://github.com/microservices-demo/catalogue/blob/master/api-spec/catalogue.json
