apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: shipping-api
  description: API for shipping operations
spec:
  type: openapi
  lifecycle: production
  owner: team-sockshop
  system: sock-shop
  definition:
    $text: https://github.com/microservices-demo/shipping/blob/master/api-spec/shipping.json
