apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-api
  description: API for user management operations
spec:
  type: openapi
  lifecycle: production
  owner: backend-team
  system: sock-shop
  definition:
    $text: https://github.com/microservices-demo/user/blob/master/api-spec/user.json
