apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: orders
  description: Orders service for Sock Shop
  annotations:
    github.com/project-slug: microservices-demo/orders
    backstage.io/kubernetes-id: orders
    backstage.io/kubernetes-namespace: sock-shop
    backstage.io/kubernetes-label-selector: "name=orders"
spec:
  type: service
  lifecycle: production
  owner: backend-team
  system: sock-shop
  providesApis:
    - orders-api
  consumesApis:
    - user-api
    - payment-api
    - shipping-api
    - cart-api
  dependsOn:
    - resource:orders-db
